export {default as Home} from "./Home"
export {default as HallRegis} from "./HallRegis"
export {default as BookTicket} from "./BookTicket"
export {default as UpdateHall} from "./UpdateHall"
export {default as Layout} from "./Layout"
export {default as Sucess} from "./Sucess"
export {default as  Cancel} from "./Cancel"